class USerModel{
  List<SearchModel> searchList=[
    SearchModel(name: "Sachin", age: "24", location: "Noida"),
    SearchModel(name: "Ravi",   age: "29", location: "Delhi"),
    SearchModel(name: "Gurgaon", age: "25", location: "Gurgaon"),
    SearchModel(name: "Arun",   age: "29", location: "Muzaffarnagar"),
    SearchModel(name: "Nitin", age: "30", location: "Sharanpur"),
    SearchModel(name: "Sunil", age: "90", location: "Meerut"),
    SearchModel(name: "Chiku", age: "80", location: "Mohali"),
    SearchModel(name: "Modi", age: "80", location: "Gujrat"),SearchModel(name: "Amit", age: "22", location: "Mumbai"),
    SearchModel(name: "Sita", age: "24", location: "Kolkata"),
    SearchModel(name: "Raj", age: "30", location: "Delhi"),
    SearchModel(name: "Pooja", age: "27", location: "Chennai"),
    SearchModel(name: "Ravi", age: "35", location: "Bangalore"),
    SearchModel(name: "Neha", age: "26", location: "Hyderabad"),
    SearchModel(name: "Vikram", age: "40", location: "Pune"),
    SearchModel(name: "Anjali", age: "29", location: "Ahmedabad"),
    SearchModel(name: "Sunil", age: "33", location: "Jaipur"),
    SearchModel(name: "Kiran", age: "28", location: "Surat"),
    SearchModel(name: "Arjun", age: "32", location: "Lucknow"),
    SearchModel(name: "Mina", age: "24", location: "Indore"),
    SearchModel(name: "Rajesh", age: "31", location: "Chandigarh"),
    SearchModel(name: "Rita", age: "25", location: "Nagpur"),
    SearchModel(name: "Manoj", age: "38", location: "Kanpur"),
    SearchModel(name: "Aarti", age: "29", location: "Visakhapatnam"),
    SearchModel(name: "Sandeep", age: "34", location: "Patna"),
    SearchModel(name: "Kavita", age: "27", location: "Coimbatore"),
    SearchModel(name: "Deepak", age: "30", location: "Bhubaneswar"),
    SearchModel(name: "Priya", age: "26", location: "Trivandrum"),
    SearchModel(name: "Suresh", age: "37", location: "Agra"),
    SearchModel(name: "Gita", age: "23", location: "Dehradun"),
    SearchModel(name: "Vijay", age: "35", location: "Shimla"),
    SearchModel(name: "Divya", age: "28", location: "Udaipur"),
    SearchModel(name: "Nitin", age: "32", location: "Raipur"),
    SearchModel(name: "Raman", age: "26", location: "Bikaner"),
    SearchModel(name: "Seema", age: "29", location: "Jodhpur"),
    SearchModel(name: "Amitabh", age: "45", location: "Jabalpur"),
    SearchModel(name: "Rohit", age: "30", location: "Ranchi"),
    SearchModel(name: "Nisha", age: "27", location: "Gwalior"),
    SearchModel(name: "Ankur", age: "33", location: "Mangalore"),
    SearchModel(name: "Kunal", age: "25", location: "Kota"),
    SearchModel(name: "Madhuri", age: "31", location: "Agartala"),
    SearchModel(name: "Sanjay", age: "38", location: "Gurgaon"),
    SearchModel(name: "Nivedita", age: "24", location: "Noida"),
    SearchModel(name: "Rakesh", age: "29", location: "Faridabad"),
    SearchModel(name: "Shruti", age: "26", location: "Kangra"),
    SearchModel(name: "Mohit", age: "32", location: "Bhopal"),
    SearchModel(name: "Sonia", age: "28", location: "Siliguri"),
    SearchModel(name: "Ravi", age: "27", location: "Panipat"),
    SearchModel(name: "Jaya", age: "30", location: "Moradabad"),
    SearchModel(name: "Amit", age: "33", location: "Gorakhpur"),
    SearchModel(name: "Rashmi", age: "25", location: "Ludhiana"),
    SearchModel(name: "Vikash", age: "29", location: "Haldwani"),
    SearchModel(name: "Neelam", age: "27", location: "Kashipur"),
    SearchModel(name: "Bharat", age: "31", location: "Mysore"),
    SearchModel(name: "Pallavi", age: "24", location: "Raigarh"),
    SearchModel(name: "Ravi", age: "28", location: "Durgapur"),
    SearchModel(name: "Kiran", age: "33", location: "Puducherry"),
    SearchModel(name: "Harish", age: "30", location: "Jalandhar"),
    SearchModel(name: "Renu", age: "26", location: "Warangal"),
    SearchModel(name: "Manisha", age: "29", location: "Kollam"),
    SearchModel(name: "Ajay", age: "32", location: "Amritsar"),
    SearchModel(name: "Sangeeta", age: "27", location: "Belgaum"),
    SearchModel(name: "Dinesh", age: "34", location: "Bhubaneswar"),
    SearchModel(name: "Shweta", age: "28", location: "Tirupati"),
    SearchModel(name: "Ashok", age: "36", location: "Kakinada"),
    SearchModel(name: "Nidhi", age: "24", location: "Bilaspur"),
    SearchModel(name: "Ravi", age: "29", location: "Sambalpur"),
    SearchModel(name: "Tanu", age: "27", location: "Mangalore"),
    SearchModel(name: "Vikram", age: "31", location: "Chittoor"),
    SearchModel(name: "Geeta", age: "32", location: "Karimnagar"),
    SearchModel(name: "Harpreet", age: "30", location: "Ferozepur"),
    SearchModel(name: "Meena", age: "25", location: "Bilaspur"),
    SearchModel(name: "Ashwini", age: "29", location: "Kolkata"),
    SearchModel(name: "Rohan", age: "28", location: "Agra"),
    SearchModel(name: "Suman", age: "27", location: "Puri"),
    SearchModel(name: "Raj", age: "34", location: "Chandigarh"),
    SearchModel(name: "Renu", age: "31", location: "Dibrugarh"),
    SearchModel(name: "Puneet", age: "26", location: "Chennai"),
    SearchModel(name: "Nisha", age: "29", location: "Delhi"),
    SearchModel(name: "Gaurav", age: "35", location: "Patna"),
    SearchModel(name: "Deepali", age: "30", location: "Jamshedpur"),
    SearchModel(name: "Sandeep", age: "28", location: "Agartala"),
    SearchModel(name: "Richa", age: "25", location: "Raipur"),
    SearchModel(name: "Suraj", age: "32", location: "Madhurai"),
    SearchModel(name: "Aarti", age: "27", location: "Kanpur"),
    SearchModel(name: "Keshav", age: "26", location: "Shimla"),
    SearchModel(name: "Sonal", age: "29", location: "Haldwani"),
    SearchModel(name: "Vikram", age: "30", location: "Jodhpur"),
    SearchModel(name: "Asha", age: "31", location: "Ranchi"),
    SearchModel(name: "Rajat", age: "28", location: "Siliguri"),
    SearchModel(name: "Diksha", age: "24", location: "Rourkela"),
    SearchModel(name: "Arun", age: "29", location: "Ludhiana"),
    SearchModel(name: "Gita", age: "30", location: "Mysore"),
    SearchModel(name: "Rajesh", age: "27", location: "Gwalior"),
    SearchModel(name: "Pooja", age: "32", location: "Coimbatore"),
    SearchModel(name: "Suresh", age: "28", location: "Surat"),
    SearchModel(name: "Sonia", age: "33", location: "Gurgaon"),
    SearchModel(name: "Tarun", age: "29", location: "Nagapattinam"),
    SearchModel(name: "Ananya", age: "24", location: "Kolkata"),
    SearchModel(name: "Sandeep", age: "30", location: "Jalandhar"),
    SearchModel(name: "Nikita", age: "27", location: "Amritsar"),
    SearchModel(name: "Raj", age: "32", location: "Vadodara"),
    SearchModel(name: "Anil", age: "35", location: "Bhopal"),

  ];
}



class SearchModel{
  final String name;
  final String age;
  final String location;
  SearchModel({required this.name, required this.age, required this.location,});
}